# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorrisJokes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChuckNorrisJokes
  pod 'RxSwift', '~> 6.0.0'
  pod 'RxCocoa', '~> 6.0.0'

  target 'ChuckNorrisJokesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChuckNorrisJokesUITests' do
    # Pods for testing
  end

end
